insert into Prompts (question_text) values
('What part of your job do you enjoy the most, and why?'),
('What part of your job feels the most draining or unmotivating?'),
('Do you feel your work is meaningful? In what ways?'),
('How confident are you in your ability to succeed in your role?'),
('Do you feel recognized for your contributions?'),
('What’s one recent win you’re proud of?'),
('How often do you feel appreciated by your team or manager?'),
('Do you feel your work makes a difference to the company?'),
('What motivates you to do your best work here?'),
('When was the last time you felt excited about a work project?'),
('How connected do you feel to your team or coworkers?'),
('What do you wish people better understood about your role?'),
('Do you feel a sense of progress in your career here?'),
('Do you believe your manager supports your success?'),
('What does a “good day” at work look like for you?'),
('When do you feel the most valued at work?'),
('Are you proud to work here? Why or why not?'),
('If you could change one thing about your job, what would it be?'),
('What tool or resource would make your day-to-day work easier?'),
('Is there a process you think could be improved or streamlined?'),
('What’s something you wish you had more time to focus on?'),
('What training or development opportunities would help you grow?'),
('How could communication in the company be improved?'),
('Are there any systems or software that feel outdated or inefficient?'),
('What’s one thing we could provide that would boost your productivity?'),
('What skill would you like to develop further?'),
('Do you have a clear understanding of what’s expected of you?'),
('How could your team collaborate more effectively?'),
('What kind of feedback helps you perform your best?'),
('Are your responsibilities clear and manageable?'),
('Do you have access to the information you need to do your job well?'),
('Is your workload currently sustainable?'),
('What would make meetings more useful for you?'),
('How could leadership better support your work?'),
('Are your goals and metrics realistic and helpful?'),
('Is there a project or idea you’d like to work on, given the chance?'),
('What’s one recurring frustration you experience at work?'),
('Are there any distractions or inefficiencies that affect your focus?'),
('Do you feel overwhelmed or stretched too thin?'),
('What’s one barrier that slows you down day-to-day?'),
('Is there a policy or rule that gets in the way of your best work?'),
('What’s something you’ve raised concerns about but felt wasn’t addressed?'),
('Are there bottlenecks or delays that impact your productivity?'),
('What’s one thing that regularly causes confusion or misalignment?'),
('Are there too many priorities competing for your attention?'),
('Do you feel safe being honest about challenges you’re facing?'),
('Is there a communication gap between teams or departments?'),
('What’s one thing that could reduce stress at work?'),
('Do you feel micromanaged, unsupported, or somewhere in between?'),
('Are there cultural or interpersonal issues that affect your work?'),
('What’s something that used to work well but doesn’t anymore?'),
('Is there anything we’re not asking that we should be asking?');
